apiVersion: v1
kind: Service
metadata:
  name: upload-ui
  namespace: demo
  labels:
    app: upload-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085
      protocol: TCP
      name: http
  selector:
    app: upload-ui
