apiVersion: v1
kind: Service
metadata:
  name: redpanda-connect
  namespace: demo
  labels:
    app: redpanda-connect
spec:
  type: NodePort
  ports:
    - port: 4195
      targetPort: 4195
      nodePort: 30195
      protocol: TCP
      name: http
  selector:
    app: redpanda-connect
